# Bibliotecas de Data Science
## Numpy

Primeiro é necessário importarmos o numpy

In [1]:
import numpy as np

### Estrutura de dados (array)

In [2]:
# podemos converter lista para numpy arrays
lista = [1, 2, 3, 4, 5]
lista_array = np.array(lista, dtype=np.int64)
lista_array

array([1, 2, 3, 4, 5])

In [3]:
# podemos converter matrizes para numpy arrays
matriz = [[1,2,3,4], [5,6,7,8]]
matriz_array = np.array(matriz, dtype=np.int64)
matriz_array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### Funções básicas

In [4]:
# matriz com todos valores 1
x = np.ones((3,4)) # argumentos tupla (linha, coluna) 
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [5]:
x.shape # dimensões da matriz

(3, 4)

In [6]:
# array em sequência
# funciona como range de python, mas retorna um numpy array
# np.arange(inicio, fim, passo)
y = np.arange(0, 1, 0.1)
y

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [7]:
# matriz com todos valores zero
z = np.zeros((3,3))
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
# matriz identidade
w = np.eye(3) # argumento é dimensão da matriz
w

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Operações básicas

In [9]:
A = np.array([[1, 1], [0, 1]])
B = np.array([[2, 0], [3, 4]])

In [10]:
A * B # produto dos elementos

array([[2, 0],
       [0, 4]])

In [11]:
A @ B # produto das matrizes

array([[5, 4],
       [3, 4]])

In [12]:
print(A.sum()) # soma de todos os valores de A
print(B.sum(axis = 0)) # soma das colunas de B
print(B.sum(axis = 1)) # soma das linhas de B

3
[5 4]
[2 7]


In [13]:
print(B.max()) # maior valor de B
print(A.min()) # menor valor de A

4
0


In [14]:
a = np.array([0, 4, 8])
np.argmax(a) # indice com maior número

2

### Random

In [15]:
# randint
# gera número inteiro aleatório dado um intervalo
np.random.randint(0,10, size=5)

array([8, 7, 5, 4, 8])

In [16]:
# random
# só contem argumento size
# gera valores aleatórios entre 0 e 1
np.random.random(size=(2,2))

array([[0.34171588, 0.36756731],
       [0.57278663, 0.57230058]])

In [17]:
# uniform
# gera matriz com valores aleatórios no intervalo (a,b)
np.random.uniform(-10, 10, size=(2,2))

array([[ 5.99798358,  1.14318788],
       [ 0.45818315, -0.06594259]])